### ISSUE TITLE
NTURGBD with these txt.files?

### ISSUE THREAD

**Issue by ztb-35** [markendo/GaitForeMer#2]
Sorry, what is the 'action_labels.txt', 'training_files.txt', ' testing_files.txt', and 'validation_files.txt'?
I downloaded the NTURGB dataset but didn't see any txt.files. 
Did you design these txt.files by yourself? Could you explain more details about this?
Thanks

**Comment by vadeli** [comment]
I have the same question. Did you figure it out?

**Comment by markendo** [comment]
The 'training_files.txt', ' testing_files.txt', and 'validation_files.txt' are generated by running `python data/NTURGDDataset.py` (in the `save_fold_files` function). I have added the 'action_labels.txt' file at data/nturgb+d_data/action_labels.txt
